package edu.poly.comon;

public enum PageType {
	USERS_MANAGEMENT_PAGE, REPORTS_MANAGEMENT_PAGE, VIDEO_MAMAGEMENT_PAGE,
	SITE_HOME_PAGE,SITE_LOGIN_PAGE,SITE_REGISTRATION_PAGE,SITE_CHANGE_PASSWORD_PAGE,
	SITE_EDIT_PROFILE_PAGE,SITE_FORGOT_PASSWORD_PAGE,SITE_VIDEO_DETAIL_PAGE,
	SITE_FAVORITE_PAGE,SITE_SHARE_PAGE
}
